// GENERATED by scripts/build-docs-index.mjs — do not edit by hand.
//
// Run `npm run docs:index` after adding or renaming a documentation heading;
// `npm run check:docs` fails when this is stale, so it cannot quietly drift
// out of step with the pages it describes.

export type DocsIndexHeading = { id: string; text: string; level: number };
export type DocsIndexPage = {
  route: string;
  title: string;
  description: string;
  /** Inline literals on the page: tool ids, env vars, chart types, fields. */
  terms: string[];
  headings: DocsIndexHeading[];
};

export const DOCS_INDEX: DocsIndexPage[] = [
  {
    "route": "/docs/account",
    "title": "Account",
    "description": "Account Settings at /account covers your identity and credentials. Spend controls live separately at /budgets.",
    "terms": [],
    "headings": [
      {
        "id": "settings",
        "text": "Account settings",
        "level": 2
      },
      {
        "id": "budgets",
        "text": "Budgets",
        "level": 2
      },
      {
        "id": "what-is-yours",
        "text": "What belongs to your account",
        "level": 2
      },
      {
        "id": "deletion",
        "text": "Deletion and departure",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/agents",
    "title": "Agent Builder",
    "description": "A complete reference for every field on an agent. Open Build → Agent Builder → New Agent; the form has six tabs, and nothing is saved until you press Save.",
    "terms": [
      "###",
      "END",
      "calculator",
      "datetime",
      "kb_graph_search",
      "kb_search",
      "llama-nemotron-rerank-vl-1b-v2",
      "mcp_call_tool",
      "metric_query",
      "n8n_run_workflow",
      "openai",
      "orders",
      "refunds",
      "sql_query",
      "weather",
      "web_browse",
      "web_search"
    ],
    "headings": [
      {
        "id": "general",
        "text": "Tab 1 — General",
        "level": 2
      },
      {
        "id": "system-prompt",
        "text": "Writing the system prompt",
        "level": 3
      },
      {
        "id": "model",
        "text": "Tab 2 — Model",
        "level": 2
      },
      {
        "id": "knowledge",
        "text": "Tab 3 — Knowledge",
        "level": 2
      },
      {
        "id": "memory",
        "text": "Tab 4 — Memory",
        "level": 2
      },
      {
        "id": "stm",
        "text": "Short-term memory — on by default",
        "level": 3
      },
      {
        "id": "ltm",
        "text": "Long-term memory — off by default",
        "level": 3
      },
      {
        "id": "guardrails",
        "text": "Tab 5 — Guardrails",
        "level": 2
      },
      {
        "id": "tools",
        "text": "Tab 6 — Tools",
        "level": 2
      },
      {
        "id": "allowed-tables",
        "text": "Allowed tables · Allowed MCP servers",
        "level": 3
      },
      {
        "id": "worked-example",
        "text": "Worked example — a support agent, start to finish",
        "level": 2
      },
      {
        "id": "versions",
        "text": "Versions",
        "level": 2
      },
      {
        "id": "export",
        "text": "Export",
        "level": 2
      },
      {
        "id": "troubleshooting",
        "text": "Troubleshooting",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/analytics",
    "title": "Analytics",
    "description": "Two views built on the same telemetry: workspace-level cost analytics at /analytics, and per-run swarm observability that replays a swarm execution node by node.",
    "terms": [
      "AUDIT_ARCHIVE_ON_PURGE",
      "ENFORCE_BUDGET_CAP",
      "PERSIST_PROMPT_BODIES",
      "audit_events",
      "audit_retention_days",
      "execution_traces",
      "maxIters",
      "model.call",
      "pricing_missing",
      "swarm.run",
      "swarm_runs",
      "tokens_estimated",
      "trace_retention_days"
    ],
    "headings": [
      {
        "id": "overview",
        "text": "Cost analytics",
        "level": 2
      },
      {
        "id": "spike",
        "text": "Tracing a spend spike",
        "level": 2
      },
      {
        "id": "swarm-observability",
        "text": "Swarm observability",
        "level": 2
      },
      {
        "id": "monitoring",
        "text": "Service monitoring",
        "level": 2
      },
      {
        "id": "audit-timeline",
        "text": "The audit timeline",
        "level": 2
      },
      {
        "id": "retention",
        "text": "Retention",
        "level": 2
      },
      {
        "id": "export",
        "text": "Export",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/api",
    "title": "API & webhooks",
    "description": "One endpoint runs a swarm from your own code: POST /api/swarm/run. Scoped keys, idempotent retries, and signed callbacks for anything slower than a request.",
    "terms": [
      "/api/notebook/run/status",
      "Idempotency-Key",
      "SWARM_RUN_MAX_CONCURRENT",
      "SWARM_RUN_RATE_LIMIT_PER_MIN",
      "SWARM_RUN_TIMEOUT_MS",
      "X-AgentSwarms-Event",
      "X-AgentSwarms-Signature",
      "X-AgentSwarms-Timestamp",
      "['run']",
      "assistant",
      "async",
      "callback_url",
      "expires_at",
      "history",
      "input",
      "inputs",
      "last_used_ip",
      "nbk_…",
      "order-48213-summary",
      "read_runs",
      "reject_approvals",
      "revoked_at",
      "rotated_from",
      "run",
      "runId",
      "scopes",
      "sha256=&lt;hex&gt;",
      "sk_swarm_…",
      "swarm.run.completed",
      "user",
      "web_browse",
      "webhook_secret"
    ],
    "headings": [
      {
        "id": "keys",
        "text": "API keys",
        "level": 2
      },
      {
        "id": "publishing",
        "text": "Which version your key runs",
        "level": 2
      },
      {
        "id": "request",
        "text": "POST /api/swarm/run",
        "level": 2
      },
      {
        "id": "req-headers",
        "text": "Headers",
        "level": 3
      },
      {
        "id": "req-body",
        "text": "Request body",
        "level": 3
      },
      {
        "id": "sync-or-async",
        "text": "Which one should you call?",
        "level": 3
      },
      {
        "id": "req-sync",
        "text": "Synchronous run",
        "level": 3
      },
      {
        "id": "req-async",
        "text": "Asynchronous run",
        "level": 3
      },
      {
        "id": "status",
        "text": "Status codes",
        "level": 2
      },
      {
        "id": "idempotency",
        "text": "Idempotency",
        "level": 2
      },
      {
        "id": "limits",
        "text": "Limits",
        "level": 2
      },
      {
        "id": "webhooks",
        "text": "Webhook callbacks",
        "level": 2
      },
      {
        "id": "verify",
        "text": "Verifying the signature",
        "level": 3
      },
      {
        "id": "outbound",
        "text": "Outbound safety",
        "level": 2
      },
      {
        "id": "approvals",
        "text": "Runs that hit an approval node",
        "level": 2
      },
      {
        "id": "observability",
        "text": "Seeing what happened",
        "level": 2
      },
      {
        "id": "notebooks",
        "text": "Calling a notebook instead of a swarm",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/bi",
    "title": "BI Workspace",
    "description": "Dashboards built on the same catalog, prepared tables and metrics your agents use — so a chart and an agent answering about it cannot disagree.",
    "terms": [
      "2.6×",
      "VITE_BI_SNAPSHOT_ROWS_CAP",
      "area",
      "avg",
      "bar",
      "barrace",
      "between",
      "boxplot",
      "bubblemap",
      "columnFormats",
      "combo",
      "compare",
      "count",
      "count_distinct",
      "currency",
      "dateGrain",
      "decimals",
      "drillFields",
      "eq",
      "forecast",
      "format",
      "funnel",
      "gauge",
      "gt",
      "gte",
      "hbar",
      "heatmap",
      "image",
      "kpi",
      "line",
      "lt",
      "lte",
      "map",
      "matrix",
      "max",
      "min",
      "neq",
      "nightingale",
      "ontology",
      "pie",
      "radar",
      "rules",
      "running",
      "sankey",
      "scale",
      "scatter",
      "scolumn",
      "shbar",
      "sum",
      "sum(amount)",
      "table",
      "text",
      "treemap",
      "trend",
      "value",
      "value2",
      "waterfall",
      "wordcloud"
    ],
    "headings": [
      {
        "id": "ai-analyst",
        "text": "AI Analyst — conversational analysis",
        "level": 2
      },
      {
        "id": "build",
        "text": "Building a dashboard",
        "level": 2
      },
      {
        "id": "generate-governed",
        "text": "Generate a dashboard from a governed model",
        "level": 3
      },
      {
        "id": "data-mode",
        "text": "How a widget gets its data",
        "level": 2
      },
      {
        "id": "row-cap",
        "text": "The row cap, and the totals it can quietly break",
        "level": 3
      },
      {
        "id": "pushdown",
        "text": "Aggregate in SQL",
        "level": 3
      },
      {
        "id": "incremental",
        "text": "Incremental refresh",
        "level": 3
      },
      {
        "id": "charts",
        "text": "Chart types — all 26, with required fields",
        "level": 2
      },
      {
        "id": "ch-basic",
        "text": "Comparison and trend",
        "level": 3
      },
      {
        "id": "ch-part",
        "text": "Part of a whole",
        "level": 3
      },
      {
        "id": "ch-single",
        "text": "Single value",
        "level": 3
      },
      {
        "id": "ch-dist",
        "text": "Distribution and relationship",
        "level": 3
      },
      {
        "id": "ch-detail",
        "text": "Tables and geography",
        "level": 3
      },
      {
        "id": "ch-special",
        "text": "Specialised",
        "level": 3
      },
      {
        "id": "non-chart-widgets",
        "text": "Two widgets that plot nothing",
        "level": 3
      },
      {
        "id": "formatting",
        "text": "Number formatting",
        "level": 2
      },
      {
        "id": "analytics",
        "text": "Analytics options",
        "level": 2
      },
      {
        "id": "condformat",
        "text": "Conditional formatting (matrix)",
        "level": 3
      },
      {
        "id": "refline",
        "text": "Reference lines",
        "level": 3
      },
      {
        "id": "interactive",
        "text": "Making it interactive",
        "level": 2
      },
      {
        "id": "insights",
        "text": "AI insights",
        "level": 2
      },
      {
        "id": "scan",
        "text": "Scan — computed, not generated",
        "level": 3
      },
      {
        "id": "alerts",
        "text": "Alerts and scheduled reports",
        "level": 2
      },
      {
        "id": "sharing",
        "text": "Sharing, export and embedding",
        "level": 2
      },
      {
        "id": "deck",
        "text": "Export as a PowerPoint deck",
        "level": 3
      },
      {
        "id": "restricted-shares",
        "text": "Row filters and hidden columns on shares",
        "level": 3
      },
      {
        "id": "lifecycle",
        "text": "Versioning and promotion",
        "level": 2
      },
      {
        "id": "performance",
        "text": "If a dashboard is slow",
        "level": 3
      }
    ]
  },
  {
    "route": "/docs/budgets",
    "title": "Budgets & cost",
    "description": "Agents spend money on every turn, and a looping graph or a public embed can spend a lot of it quickly. Caps are the control that turns a bad day into a stopped run.",
    "terms": [
      "$12.34+?",
      "BUDGET_FAIL_CLOSED=true",
      "ENFORCE_BUDGET_CAP",
      "ENFORCE_BUDGET_CAP=true",
      "budget_settings.monthly_cap_usd",
      "embed_key",
      "group",
      "is_active",
      "monthly_cap_usd",
      "pricing_missing",
      "swarm_api_key",
      "tokens_estimated",
      "true",
      "usage",
      "yes"
    ],
    "headings": [
      {
        "id": "what-costs",
        "text": "What actually costs money",
        "level": 2
      },
      {
        "id": "caps",
        "text": "Setting caps",
        "level": 2
      },
      {
        "id": "cap-user",
        "text": "Per-user cap",
        "level": 3
      },
      {
        "id": "cap-scoped",
        "text": "Scoped caps",
        "level": 3
      },
      {
        "id": "enforcement",
        "text": "Enforcement is opt-in",
        "level": 3
      },
      {
        "id": "worked",
        "text": "Worked example: a support bot on a public site",
        "level": 2
      },
      {
        "id": "how-cost-is-computed",
        "text": "How a number becomes a cost",
        "level": 2
      },
      {
        "id": "cost-tokens",
        "text": "Tokens: measured, or approximated",
        "level": 3
      },
      {
        "id": "cost-price",
        "text": "Price: resolved per provider, per model",
        "level": 3
      },
      {
        "id": "reduce",
        "text": "Reducing spend",
        "level": 2
      },
      {
        "id": "retention",
        "text": "Retention",
        "level": 2
      },
      {
        "id": "alerts",
        "text": "Alerts",
        "level": 3
      },
      {
        "id": "attribution",
        "text": "Attribution",
        "level": 3
      }
    ]
  },
  {
    "route": "/docs/concepts",
    "title": "Core concepts",
    "description": "The words this platform uses, and what each one corresponds to mechanically. Worth twenty minutes — most agent problems are really a misunderstanding of one of these.",
    "terms": [
      "calculator",
      "datetime",
      "kb_graph_search",
      "kb_search",
      "mcp_call_tool",
      "metric_query",
      "n8n_run_workflow",
      "sql_query",
      "weather",
      "web_browse",
      "web_search"
    ],
    "headings": [
      {
        "id": "model",
        "text": "The model, and what it can't do",
        "level": 2
      },
      {
        "id": "agent",
        "text": "Agent",
        "level": 2
      },
      {
        "id": "tools",
        "text": "Tools",
        "level": 2
      },
      {
        "id": "retrieval",
        "text": "Retrieval, or \"RAG\"",
        "level": 2
      },
      {
        "id": "swarm",
        "text": "Swarm",
        "level": 2
      },
      {
        "id": "memory",
        "text": "Memory",
        "level": 2
      },
      {
        "id": "guardrails",
        "text": "Guardrails",
        "level": 2
      },
      {
        "id": "byok",
        "text": "BYOK — whose key pays",
        "level": 2
      },
      {
        "id": "traces",
        "text": "Traces",
        "level": 2
      },
      {
        "id": "choosing",
        "text": "Which one do I actually want?",
        "level": 2
      },
      {
        "id": "glossary",
        "text": "Quick glossary",
        "level": 3
      }
    ]
  },
  {
    "route": "/docs/dashboard",
    "title": "Dashboard",
    "description": "The dashboard at /dashboard is the screen you land on after signing in. It answers two questions: what is the fastest next thing to do, and what has been happening in your workspace.",
    "terms": [],
    "headings": [
      {
        "id": "quick-actions",
        "text": "Quick actions",
        "level": 2
      },
      {
        "id": "featured-swarms",
        "text": "Featured swarms",
        "level": 2
      },
      {
        "id": "stats",
        "text": "Workspace stats",
        "level": 2
      },
      {
        "id": "spend",
        "text": "Spend & usage — by person, team or organisation",
        "level": 2
      },
      {
        "id": "activity",
        "text": "Activity and model mix",
        "level": 2
      },
      {
        "id": "recent-runs",
        "text": "Recent runs",
        "level": 2
      },
      {
        "id": "first-run",
        "text": "What to do on a new workspace",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/data-prep",
    "title": "Data preparation",
    "description": "Raw tables rarely answer a question on their own. Prep joins them, fixes the columns and saves the whole recipe so tomorrow's data goes through the same steps.",
    "terms": [
      "AND",
      "CASE",
      "OR",
      "SELECT",
      "aggregate",
      "all",
      "amount",
      "append",
      "boolean",
      "calc",
      "category",
      "contains",
      "currency",
      "date",
      "date_trunc",
      "decimal",
      "dedupe",
      "distinct",
      "filter",
      "id",
      "integer",
      "list_aggregate",
      "location",
      "order_id",
      "order_month",
      "percent",
      "pivot",
      "product",
      "regexp_extract",
      "replace",
      "split",
      "strftime",
      "text",
      "unpivot"
    ],
    "headings": [
      {
        "id": "canvas",
        "text": "The canvas",
        "level": 2
      },
      {
        "id": "joins",
        "text": "Joins",
        "level": 2
      },
      {
        "id": "column-types",
        "text": "Column types",
        "level": 2
      },
      {
        "id": "steps",
        "text": "The nine steps",
        "level": 2
      },
      {
        "id": "calc-expressions",
        "text": "Writing a calculated field",
        "level": 3
      },
      {
        "id": "filter-ops",
        "text": "Filter operators",
        "level": 3
      },
      {
        "id": "worked",
        "text": "Worked example — a messy export to a monthly table",
        "level": 2
      },
      {
        "id": "save-refresh",
        "text": "Saving and refreshing",
        "level": 2
      },
      {
        "id": "lineage",
        "text": "Lineage",
        "level": 3
      },
      {
        "id": "when-not",
        "text": "When not to use prep",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/data",
    "title": "Data Catalog & SQL",
    "description": "Everything tabular: uploaded files, 22 databases and warehouses, 5 app sources, the catalog that describes them, and the workbench that queries them.",
    "terms": [
      ".avro",
      ".csv",
      ".xlsx",
      "2024-03-01",
      "AwsDataCatalog",
      "HTTPS_PROXY",
      "LIST",
      "MAP",
      "NO_PROXY",
      "ORC_MAX_DOWNLOAD_BYTES",
      "ORDS.ENABLE_SCHEMA",
      "SELECT",
      "SQLEXPRESS",
      "STRUCT",
      "UPLOAD_MAX_ROWS",
      "access_key_id",
      "access_token",
      "account",
      "calculator",
      "catalog",
      "cluster_identifier",
      "data/orders.parquet",
      "database",
      "dataset",
      "db_user",
      "disable",
      "host",
      "https://abc.clickhouse.cloud:8443",
      "instance_name",
      "location",
      "monthly_revenue",
      "myorg-myaccount",
      "orders",
      "ords_url",
      "output_location",
      "password",
      "port",
      "primary",
      "project_id",
      "read_orc",
      "read_orc(&apos;s3://…&apos;)",
      "read_parquet(&apos;s3://…&apos;)",
      "region",
      "require",
      "role",
      "s3://",
      "s3://bucket/prefix/",
      "sales",
      "sales/*.parquet",
      "schema",
      "secret_access_key",
      "server",
      "service_account_json",
      "session_token",
      "sheet1",
      "sql_query",
      "ssl",
      "tedious",
      "token",
      "true",
      "trust_server_certificate",
      "url",
      "us-central1",
      "username",
      "warehouse",
      "warehouse_id",
      "workgroup",
      "workgroup_name",
      "xy12345.eu-west-1"
    ],
    "headings": [
      {
        "id": "choosing",
        "text": "Which kind of source do you want?",
        "level": 2
      },
      {
        "id": "local-tables",
        "text": "Local tables",
        "level": 2
      },
      {
        "id": "connectors",
        "text": "External connections — every field",
        "level": 2
      },
      {
        "id": "c-other",
        "text": "Object stores and lakehouse catalogs",
        "level": 3
      },
      {
        "id": "direct-vs-import",
        "text": "Direct query vs import",
        "level": 3
      },
      {
        "id": "sharing",
        "text": "Sharing a connection with your team",
        "level": 2
      },
      {
        "id": "apps",
        "text": "Apps — SaaS sources",
        "level": 2
      },
      {
        "id": "reliability",
        "text": "Staying connected",
        "level": 2
      },
      {
        "id": "catalog",
        "text": "The catalog",
        "level": 2
      },
      {
        "id": "workbench",
        "text": "SQL workbench",
        "level": 2
      },
      {
        "id": "workbench-engine",
        "text": "Which engine runs your SQL",
        "level": 3
      },
      {
        "id": "workbench-first-query",
        "text": "The first query in a session is slower",
        "level": 3
      },
      {
        "id": "agent-access",
        "text": "Giving an agent access",
        "level": 2
      },
      {
        "id": "troubleshooting",
        "text": "Troubleshooting",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/debugging",
    "title": "Logs & traces",
    "description": "Every run on the platform — playground chats, swarm nodes, notebook calls — is recorded as a trace. Reading traces is the core debugging skill in agentic systems, and the one course environments almost never let you practice.",
    "terms": [
      "PERSIST_PROMPT_BODIES",
      "false",
      "sql_query",
      "trace_retention_days"
    ],
    "headings": [
      {
        "id": "traces-table",
        "text": "The traces table",
        "level": 2
      },
      {
        "id": "trace-detail",
        "text": "What a trace contains",
        "level": 2
      },
      {
        "id": "playground-inspector",
        "text": "The playground inspector",
        "level": 2
      },
      {
        "id": "method",
        "text": "Three habits",
        "level": 2
      },
      {
        "id": "symptoms",
        "text": "Symptom to cause",
        "level": 2
      },
      {
        "id": "reading",
        "text": "A debugging order that works",
        "level": 2
      },
      {
        "id": "swarm-traces",
        "text": "Swarm traces",
        "level": 2
      },
      {
        "id": "swarm-inspector",
        "text": "Reading a run: three views, then one step",
        "level": 3
      },
      {
        "id": "prompt-bodies",
        "text": "Retention, and what a regulated tenant can turn off",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/embedding",
    "title": "Web embedding",
    "description": "Publish an agent, a swarm or a dashboard to your own site — where the visitors are anonymous, which changes what you must think about.",
    "terms": [
      "&lt;AgentChat&gt;",
      "--as-accent",
      "--as-accent-fg",
      "--as-bg",
      "--as-border",
      "--as-bubble",
      "--as-fg",
      "--as-muted",
      "--as-radius",
      "/embed/agent/",
      "/embed/agent/&lt;key&gt;",
      "/embed/analyst/&lt;key&gt;",
      "/embed/bi/",
      "/embed/bi/&lt;key&gt;",
      "/embed/swarm/&lt;key&gt;",
      "?vt=…",
      "ENFORCE_BUDGET_CAP",
      "Origin",
      "POST",
      "activeTurn",
      "agent",
      "allow_ai",
      "allowed_domains",
      "bi_dashboard",
      "createSseParser",
      "docs.example.com",
      "emk_",
      "error",
      "expires_at",
      "https://example.com",
      "https://www.example.com",
      "iframe",
      "is_active",
      "last_used_at",
      "mapAnalystFrame",
      "mapChatFrame",
      "region",
      "resource_type",
      "sdk/react",
      "swarm",
      "tenant",
      "transcript_retention_days",
      "turns",
      "useAgentChat",
      "use_count",
      "www.",
      "www.example.com"
    ],
    "headings": [
      {
        "id": "setup",
        "text": "Setting one up",
        "level": 2
      },
      {
        "id": "key-fields",
        "text": "Every field on an embed key",
        "level": 3
      },
      {
        "id": "react-sdk",
        "text": "Two ways to embed: iframe or React SDK",
        "level": 2
      },
      {
        "id": "sdk-install",
        "text": "Installing",
        "level": 3
      },
      {
        "id": "sdk-drop-in",
        "text": "The drop-in component",
        "level": 3
      },
      {
        "id": "sdk-hooks",
        "text": "The headless hooks",
        "level": 3
      },
      {
        "id": "sdk-key-safety",
        "text": "The embed key is still public",
        "level": 3
      },
      {
        "id": "what-visitors-get",
        "text": "What an anonymous visitor can reach",
        "level": 2
      },
      {
        "id": "security",
        "text": "How access is enforced",
        "level": 2
      },
      {
        "id": "transcripts",
        "text": "Transcripts and retention",
        "level": 2
      },
      {
        "id": "dashboards",
        "text": "Embedded dashboards",
        "level": 2
      },
      {
        "id": "signed-viewers",
        "text": "Signed viewers — one dashboard, many customers",
        "level": 3
      },
      {
        "id": "visual-answers",
        "text": "Visual answers in embeds",
        "level": 3
      },
      {
        "id": "analyst",
        "text": "Embedding the AI Analyst",
        "level": 2
      },
      {
        "id": "limits",
        "text": "What one visitor can consume",
        "level": 2
      },
      {
        "id": "troubleshooting",
        "text": "When an embed does not work",
        "level": 2
      },
      {
        "id": "checklist",
        "text": "Pre-publish checklist",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/guardrails",
    "title": "Guardrails & PII",
    "description": "Checks that run outside the model, on the way in and on the way out — which is why they still hold when someone talks the agent out of its instructions.",
    "terms": [
      "[REDACTED_EMAIL]",
      "api_key",
      "blockPII",
      "credit_card",
      "dob",
      "email",
      "iban",
      "ip",
      "phone",
      "ssn"
    ],
    "headings": [
      {
        "id": "reference",
        "text": "Complete field reference",
        "level": 2
      },
      {
        "id": "content-safety",
        "text": "Content safety",
        "level": 3
      },
      {
        "id": "input",
        "text": "Input filtering",
        "level": 3
      },
      {
        "id": "output",
        "text": "Output filtering",
        "level": 3
      },
      {
        "id": "limits",
        "text": "Conversation limits",
        "level": 3
      },
      {
        "id": "pii",
        "text": "Personal data",
        "level": 2
      },
      {
        "id": "pii-modes",
        "text": "Modes",
        "level": 3
      },
      {
        "id": "pii-entities",
        "text": "The eight detectors",
        "level": 3
      },
      {
        "id": "legacy",
        "text": "Legacy setting",
        "level": 3
      },
      {
        "id": "recipes",
        "text": "Configuration recipes",
        "level": 2
      },
      {
        "id": "recipe-public",
        "text": "Public website embed",
        "level": 3
      },
      {
        "id": "recipe-internal",
        "text": "Internal analyst agent",
        "level": 3
      },
      {
        "id": "recipe-regulated",
        "text": "Regulated / high-sensitivity",
        "level": 3
      },
      {
        "id": "where",
        "text": "Where guardrails apply",
        "level": 2
      },
      {
        "id": "testing",
        "text": "Testing yours",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/iam",
    "title": "Access control",
    "description": "Provision people, put them in groups, control which models they may run, and share data read-only — enforced in the database, not just hidden in the interface.",
    "terms": [
      "ADMIN_EMAIL",
      "analytics",
      "gpt-4o",
      "gpt-4o-mini",
      "openai",
      "openai/*",
      "openrouter",
      "region",
      "revenue",
      "salary"
    ],
    "headings": [
      {
        "id": "tabs",
        "text": "The seven tabs",
        "level": 2
      },
      {
        "id": "roles",
        "text": "Roles",
        "level": 2
      },
      {
        "id": "users",
        "text": "Users",
        "level": 2
      },
      {
        "id": "groups",
        "text": "Groups",
        "level": 2
      },
      {
        "id": "model-rules",
        "text": "Model rules",
        "level": 2
      },
      {
        "id": "sharing",
        "text": "Resource sharing",
        "level": 2
      },
      {
        "id": "row-column-security",
        "text": "Narrowing a grant: row filters and column masks",
        "level": 3
      },
      {
        "id": "attributes",
        "text": "One grant, per-viewer rows: user attributes",
        "level": 3
      },
      {
        "id": "shared-connections",
        "text": "Shared connections run as their owner",
        "level": 3
      },
      {
        "id": "signup",
        "text": "Signup policy and SSO",
        "level": 2
      },
      {
        "id": "worked",
        "text": "Worked example — onboarding an analytics team",
        "level": 3
      },
      {
        "id": "rollout",
        "text": "A sensible rollout",
        "level": 3
      }
    ]
  },
  {
    "route": "/docs",
    "title": "Documentation",
    "description": "AgentSwarms is a platform for building agentic AI on your own data — agents and multi-agent swarms, the knowledge and tables they work from, the dashboards beside them, and the controls that make all of it safe to hand to other people.",
    "terms": [],
    "headings": [
      {
        "id": "start-here",
        "text": "Start here",
        "level": 2
      },
      {
        "id": "by-job",
        "text": "Find it by what you're doing",
        "level": 2
      },
      {
        "id": "orient",
        "text": "Get oriented",
        "level": 3
      },
      {
        "id": "build",
        "text": "Build something",
        "level": 3
      },
      {
        "id": "data",
        "text": "Work with data",
        "level": 3
      },
      {
        "id": "ship",
        "text": "Ship and integrate",
        "level": 3
      },
      {
        "id": "govern",
        "text": "Govern and operate",
        "level": 3
      },
      {
        "id": "principles",
        "text": "Three things worth knowing up front",
        "level": 2
      },
      {
        "id": "help",
        "text": "When the docs do not have it",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/integrations",
    "title": "Integrations",
    "description": "The Integration Hub at /integrations connects AgentSwarms to outside model providers and automation; /mcp connects it to tool servers. Keys are stored server-side and used only by the runtime — they are never sent back to the browser.",
    "terms": [
      "/api/slack/command",
      "/ask",
      "/models",
      "FIRECRAWL_API_KEY",
      "T01AB2CD3EF",
      "localhost",
      "web_browse",
      "web_search"
    ],
    "headings": [
      {
        "id": "builtin",
        "text": "The default provider first",
        "level": 2
      },
      {
        "id": "providers",
        "text": "LLM providers (bring your own key)",
        "level": 2
      },
      {
        "id": "gateway",
        "text": "LLM Gateway",
        "level": 2
      },
      {
        "id": "shared",
        "text": "Shared credentials (teams)",
        "level": 2
      },
      {
        "id": "resolution",
        "text": "Which key actually pays",
        "level": 3
      },
      {
        "id": "websearch",
        "text": "Web search & browsing",
        "level": 2
      },
      {
        "id": "slack",
        "text": "Ask an AI Analyst from Slack",
        "level": 2
      },
      {
        "id": "notifications",
        "text": "Notification channels",
        "level": 2
      },
      {
        "id": "n8n",
        "text": "n8n workflows",
        "level": 2
      },
      {
        "id": "mcp",
        "text": "MCP servers",
        "level": 2
      },
      {
        "id": "categories",
        "text": "What can be connected",
        "level": 2
      },
      {
        "id": "credentials",
        "text": "Credential handling",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/knowledge",
    "title": "Knowledge Base",
    "description": "Collections of documents an agent can search by meaning and quote with citations. This is how you stop an agent inventing your policies.",
    "terms": [
      "/embeddings",
      "/models",
      "GITHUB_TOKEN",
      "OPENROUTER_API_KEY",
      "error",
      "final_v3.pdf",
      "flat",
      "google/gemini-embedding-001",
      "kb_graph_search",
      "kb_search",
      "llama-nemotron-rerank-vl-1b-v2",
      "ok",
      "openai/text-embedding-3-large",
      "openai/text-embedding-3-small",
      "parent_child",
      "qa",
      "qwen/qwen3-embedding-4b",
      "qwen/qwen3-embedding-8b",
      "refund-policy-2026.pdf",
      "resolveEmbedTarget",
      "text-embedding-3-*"
    ],
    "headings": [
      {
        "id": "sources",
        "text": "Adding sources",
        "level": 2
      },
      {
        "id": "s-file",
        "text": "File upload",
        "level": 3
      },
      {
        "id": "s-url",
        "text": "Web page / crawl",
        "level": 3
      },
      {
        "id": "s-github",
        "text": "GitHub repository",
        "level": 3
      },
      {
        "id": "s-manual",
        "text": "Pasted text",
        "level": 3
      },
      {
        "id": "s-connectors",
        "text": "Connected services — Drive, Notion, SharePoint, Dropbox",
        "level": 3
      },
      {
        "id": "scheduled-sync",
        "text": "Scheduled sync — indexing without duplicates",
        "level": 2
      },
      {
        "id": "pipeline",
        "text": "What happens on ingest",
        "level": 2
      },
      {
        "id": "embedding-provider",
        "text": "Which model does the embedding",
        "level": 3
      },
      {
        "id": "chunk-modes",
        "text": "Chunking modes",
        "level": 2
      },
      {
        "id": "hybrid",
        "text": "Hybrid search and weighting",
        "level": 2
      },
      {
        "id": "retrieval",
        "text": "Retrieval settings — the real numbers",
        "level": 2
      },
      {
        "id": "reranking",
        "text": "Reranking",
        "level": 3
      },
      {
        "id": "recipes",
        "text": "Configuration by what you are indexing",
        "level": 2
      },
      {
        "id": "recipe-policy",
        "text": "Policies, contracts, handbooks",
        "level": 3
      },
      {
        "id": "recipe-docs",
        "text": "Product documentation and how-to guides",
        "level": 3
      },
      {
        "id": "recipe-support",
        "text": "Support tickets and FAQs",
        "level": 3
      },
      {
        "id": "recipe-code",
        "text": "A code repository",
        "level": 3
      },
      {
        "id": "recipe-mixed",
        "text": "One collection holding several kinds at once",
        "level": 3
      },
      {
        "id": "using",
        "text": "Attaching a collection to an agent",
        "level": 2
      },
      {
        "id": "graph",
        "text": "Graph search",
        "level": 2
      },
      {
        "id": "sharing",
        "text": "Sharing and access",
        "level": 2
      },
      {
        "id": "access-scopes",
        "text": "Per-source access scopes",
        "level": 3
      },
      {
        "id": "debugging",
        "text": "When an answer is wrong",
        "level": 2
      },
      {
        "id": "quality",
        "text": "Getting better results",
        "level": 3
      }
    ]
  },
  {
    "route": "/docs/mcp",
    "title": "MCP servers",
    "description": "The Model Context Protocol is a standard way for a system to expose its tools to any agent. Connect one and its tools become available to yours.",
    "terms": [
      "/api/mcp/s/&lt;slug&gt;",
      "404",
      "405",
      "@mcp.tool",
      "@mcp.tool()",
      "BLOCK_PRIVATE_NETWORK_FETCH",
      "DELETE",
      "INTERNAL_API_TOKEN",
      "Mcp-Session-Id",
      "PUBLIC_APP_URL",
      "agentswarms",
      "api.internal.example.com",
      "app",
      "auth_token",
      "auth_type",
      "cancelled",
      "description",
      "endpoint",
      "fastmcp",
      "greet",
      "httpx",
      "initialize",
      "initialized",
      "langchain",
      "langgraph",
      "last_ping",
      "llama_index",
      "mcp",
      "mcp.run()",
      "mcp.server.fastmcp.FastMCP",
      "mcp_call_tool",
      "name",
      "none",
      "numpy",
      "os.environ",
      "pandas",
      "ping",
      "pydantic",
      "requirements.txt",
      "server",
      "server_name",
      "status",
      "token",
      "tools/call",
      "tools/list",
      "tools_count",
      "trust_env=True"
    ],
    "headings": [
      {
        "id": "connect",
        "text": "Connecting a server",
        "level": 2
      },
      {
        "id": "server-fields",
        "text": "Every field on a server",
        "level": 3
      },
      {
        "id": "how-agents-use",
        "text": "How an agent uses it",
        "level": 2
      },
      {
        "id": "security",
        "text": "Security",
        "level": 2
      },
      {
        "id": "build",
        "text": "Building your own MCP server",
        "level": 2
      },
      {
        "id": "build-ai",
        "text": "Writing the server with AI",
        "level": 3
      },
      {
        "id": "build-contract",
        "text": "What the runner expects",
        "level": 3
      },
      {
        "id": "build-secrets",
        "text": "Using a secret, and reaching a real API",
        "level": 3
      },
      {
        "id": "build-lifecycle",
        "text": "Cold starts and keep-warm",
        "level": 3
      },
      {
        "id": "build-access",
        "text": "Who can call it",
        "level": 3
      },
      {
        "id": "build-client",
        "text": "Pointing an external client at it",
        "level": 3
      },
      {
        "id": "build-security",
        "text": "How a built server is contained",
        "level": 3
      },
      {
        "id": "build-troubleshooting",
        "text": "When a build won't start",
        "level": 3
      },
      {
        "id": "troubleshooting",
        "text": "Troubleshooting a connected server",
        "level": 3
      }
    ]
  },
  {
    "route": "/docs/models",
    "title": "Models & providers",
    "description": "Which models your workspace can reach, whose account pays for them, and how to pick sensibly between them.",
    "terms": [
      "2024-08-01-preview",
      "BLOCK_PRIVATE_NETWORK_FETCH",
      "accessKeyId",
      "anthropic",
      "apiKey",
      "apiVersion",
      "azure_openai",
      "baseUrl",
      "bedrock",
      "compartmentId",
      "endpoint",
      "fingerprint",
      "gemini",
      "gpt-4o",
      "grok",
      "groq",
      "http://host.docker.internal:11434",
      "http://localhost:11434",
      "https://my-resource.openai.azure.com",
      "localhost",
      "location",
      "nvidia",
      "oci_genai",
      "ollama",
      "openai",
      "openrouter",
      "privateKeyPem",
      "prod-chat",
      "projectId",
      "qwen",
      "region",
      "secretAccessKey",
      "serviceAccountJson",
      "sessionToken",
      "style",
      "tenancyOcid",
      "userOcid",
      "vertex",
      "vllm"
    ],
    "headings": [
      {
        "id": "byok",
        "text": "Bring your own key",
        "level": 2
      },
      {
        "id": "providers",
        "text": "Supported providers — all 14",
        "level": 3
      },
      {
        "id": "cloud-config",
        "text": "Configuring the cloud providers",
        "level": 3
      },
      {
        "id": "local-config",
        "text": "Keeping inference on your own machines",
        "level": 3
      },
      {
        "id": "registry",
        "text": "Model registry",
        "level": 2
      },
      {
        "id": "choosing",
        "text": "Choosing a model",
        "level": 2
      },
      {
        "id": "params",
        "text": "Temperature and tokens",
        "level": 3
      },
      {
        "id": "fallback",
        "text": "Overrides and fallback",
        "level": 2
      },
      {
        "id": "cost",
        "text": "Cost",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/notebooks",
    "title": "Developer workspace",
    "description": "Python notebooks at /notebooks that execute on sandboxed server kernels — real CPython with pip and the agentic frameworks pre-installed. Start from read-only framework samples, or write your own and call models and knowledge bases through your account.",
    "terms": [
      ".json",
      "202",
      "NOTEBOOK_CRON_TOKEN",
      "NOTEBOOK_GATEWAY_URL",
      "NOTEBOOK_RUNTIME_BACKEND",
      "NOTEBOOK_RUNTIME_ENABLED",
      "NOTEBOOK_RUNTIME_IMAGE",
      "NOTEBOOK_RUNTIME_SECRET",
      "PIP_USER=1",
      "async",
      "build-essential",
      "chat",
      "entrypoint",
      "error",
      "inputs",
      "queued",
      "result",
      "runId",
      "run_swarm",
      "running",
      "succeeded",
      "~/.local"
    ],
    "headings": [
      {
        "id": "samples",
        "text": "Framework samples",
        "level": 2
      },
      {
        "id": "fork",
        "text": "Read-only & fork",
        "level": 2
      },
      {
        "id": "how-cells-run",
        "text": "How cells run",
        "level": 2
      },
      {
        "id": "helper",
        "text": "The agentswarms helper",
        "level": 2
      },
      {
        "id": "where-they-fit",
        "text": "Where the workspace fits",
        "level": 2
      },
      {
        "id": "which-surface",
        "text": "Notebook, agent, or swarm?",
        "level": 3
      },
      {
        "id": "runtimes",
        "text": "There is one runtime, and it is off by default",
        "level": 2
      },
      {
        "id": "libraries",
        "text": "Installing libraries",
        "level": 3
      },
      {
        "id": "egress",
        "text": "Kernel network isolation",
        "level": 2
      },
      {
        "id": "run-agent",
        "text": "Calling your deployed agents and swarms",
        "level": 3
      },
      {
        "id": "publish",
        "text": "Publishing a notebook as an API",
        "level": 2
      },
      {
        "id": "versioning",
        "text": "Version control (Git)",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/playground",
    "title": "Agent Chat",
    "description": "The playground at /playground is where you talk to agents directly. It looks like a chat app; the difference is that every message produces a trace you can inspect, and the agent runs with its full saved configuration — same tools, same guardrails, same memory as anywhere else on the platform.",
    "terms": [
      "tools.biVisuals"
    ],
    "headings": [
      {
        "id": "chatting",
        "text": "Chatting with an agent",
        "level": 2
      },
      {
        "id": "traces",
        "text": "The trace behind every message",
        "level": 2
      },
      {
        "id": "skill-samples",
        "text": "Skill-sample agents",
        "level": 2
      },
      {
        "id": "composer",
        "text": "Composer controls — every button",
        "level": 2
      },
      {
        "id": "sources",
        "text": "Sources under an answer",
        "level": 2
      },
      {
        "id": "docgen",
        "text": "Generating documents",
        "level": 2
      },
      {
        "id": "docgen-modes",
        "text": "Browser vs Deep",
        "level": 3
      },
      {
        "id": "image-playground",
        "text": "Image Playground",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/quickstart",
    "title": "Quickstart",
    "description": "Thirty minutes, five steps. At the end you'll have an agent that answers from your own documents and data, and you'll know how to check whether its answer was honest.",
    "terms": [
      "OPENROUTER_API_KEY",
      "refunds.csv",
      "sql_query",
      "web_search"
    ],
    "headings": [
      {
        "id": "step-0",
        "text": "Before you start: one model provider",
        "level": 2
      },
      {
        "id": "step-1",
        "text": "1. Talk to something that already works",
        "level": 2
      },
      {
        "id": "step-2",
        "text": "2. Give the platform something to work with",
        "level": 2
      },
      {
        "id": "step-3",
        "text": "3. Build the agent",
        "level": 2
      },
      {
        "id": "step-4",
        "text": "4. Run it and read the sources",
        "level": 2
      },
      {
        "id": "generate-a-document",
        "text": "Generate a document",
        "level": 3
      },
      {
        "id": "step-5",
        "text": "5. Read the trace",
        "level": 2
      },
      {
        "id": "first-run-problems",
        "text": "If the first run doesn't work",
        "level": 2
      },
      {
        "id": "where-next",
        "text": "Where to go next",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/secrets",
    "title": "Secrets",
    "description": "A vault for the credentials the platform uses on your behalf. Store once, reference by name, rotate in one place.",
    "terms": [
      "200",
      "2captcha_key",
      "BILLING_STRIPE_KEY",
      "PROVIDER_CREDS_SECRET",
      "SNOWFLAKE_ANALYTICS_RO",
      "SNOWFLAKE_ANALYTICS_RO_V2",
      "STRIPE_KEY",
      "SUPPORT_STRIPE_KEY",
      "^[A-Za-z][A-Za-z0-9_]*$",
      "jiraToken",
      "key2",
      "snowflake-analytics-ro",
      "snowflake_analytics_ro",
      "stripe_live_key"
    ],
    "headings": [
      {
        "id": "using",
        "text": "Creating and referencing",
        "level": 2
      },
      {
        "id": "naming",
        "text": "Name rules",
        "level": 3
      },
      {
        "id": "referencing",
        "text": "Referencing a secret by name",
        "level": 2
      },
      {
        "id": "where-refs-resolve",
        "text": "Exactly which fields resolve",
        "level": 3
      },
      {
        "id": "resolution-failures",
        "text": "When a reference cannot be resolved",
        "level": 3
      },
      {
        "id": "rotating",
        "text": "Worked example — rotating a warehouse password",
        "level": 3
      },
      {
        "id": "where",
        "text": "Where secrets can be used",
        "level": 2
      },
      {
        "id": "access",
        "text": "Access",
        "level": 2
      },
      {
        "id": "hygiene",
        "text": "Hygiene",
        "level": 2
      },
      {
        "id": "at-rest",
        "text": "How they're protected",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/self-hosting",
    "title": "Install & deploy",
    "description": "Run the whole platform on your own infrastructure. You need a Supabase project for the database and auth, and either Docker or Node.",
    "terms": [
      "--all",
      "--dev",
      "--docgen",
      "--notebooks",
      "--sandbox",
      ".env",
      ".env.example",
      "ADMIN_EMAIL",
      "ALLOW_PRIVATE_NETWORK_FETCH",
      "AUDIT_ARCHIVE_ON_PURGE",
      "BI_CRON_TOKEN",
      "BI_DIRECT_QUERY_RATE_PER_MIN",
      "BLOCK_PRIVATE_NETWORK_FETCH",
      "BUDGET_FAIL_CLOSED",
      "CONNECTION_HEALTH_HOURS",
      "CONNECTOR_MAX_RETRIES",
      "CONNECTOR_RETRY_500",
      "CONNECTOR_RETRY_BASE_MS",
      "CONNECTOR_RETRY_MAX_MS",
      "CREDENTIAL_MAX_AGE_DAYS",
      "DISABLE_INPROCESS_SCHEDULER",
      "DOCGEN_SERVICE_URL",
      "DOCGEN_TOKEN",
      "EMAIL_FROM",
      "ENFORCE_BUDGET_CAP",
      "FIRECRAWL_API_KEY",
      "HTTPS_PROXY",
      "HTTP_PROXY",
      "INTEGRATION_TEST_PER_MINUTE",
      "INTERNAL_RUN_SECRET",
      "JS_SANDBOX_MAX_BODY_BYTES",
      "JS_SANDBOX_MAX_CONCURRENT",
      "JS_SANDBOX_MAX_TIMEOUT_MS",
      "JS_SANDBOX_MEM_MB",
      "JS_SANDBOX_URL",
      "LOCAL_ENGINE_MEMORY_MB",
      "LOCAL_ENGINE_THREADS",
      "LOCAL_ENGINE_TIMEOUT_MS",
      "MCP_MAX_CONCURRENT_PER_SERVER",
      "METRICS_TOKEN",
      "MIRROR_BUDGET_BYTES",
      "NOTEBOOK_CELL_TIMEOUT_SECONDS",
      "NOTEBOOK_CRON_TOKEN",
      "NOTEBOOK_GATEWAY_URL",
      "NOTEBOOK_RUNTIME_BACKEND",
      "NOTEBOOK_RUNTIME_ENABLED",
      "NOTEBOOK_RUNTIME_IMAGE",
      "NOTEBOOK_RUNTIME_SECRET",
      "OPENAI_API_KEY",
      "OPENROUTER_API_KEY",
      "OPENROUTER_BASE_URL",
      "OPENROUTER_DEFAULT_MODEL",
      "OTEL_EXPORTER_OTLP_ENDPOINT",
      "OTEL_EXPORTER_OTLP_HEADERS",
      "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT",
      "OTEL_SERVICE_NAME",
      "PARQUET_CACHE_DIR",
      "PARQUET_CACHE_MAX_BYTES",
      "PARQUET_MAX_ROWS",
      "PARQUET_MIN_ROWS",
      "PARQUET_MIRROR",
      "PERSIST_PROMPT_BODIES",
      "PROVIDER_CREDS_SECRET",
      "PROVIDER_CREDS_SECRET_OLD",
      "PUBLIC_APP_URL",
      "RESEND_API_KEY",
      "SITE_URL",
      "SMTP_HOST",
      "SMTP_PASS",
      "SMTP_PORT",
      "SMTP_SECURE",
      "SMTP_USER",
      "SUPABASE_PUBLISHABLE_KEY",
      "SUPABASE_SERVICE_ROLE_KEY",
      "SUPABASE_URL",
      "SWARM_LEVEL_CONCURRENCY",
      "SWARM_RUN_MAX_CONCURRENT",
      "SWARM_RUN_RATE_LIMIT_PER_MIN",
      "SWARM_RUN_TIMEOUT_MS",
      "TRUSTED_PROXY_HOPS",
      "UPLOAD_PER_MINUTE",
      "VITE_ADMIN_EMAIL",
      "VITE_SUPABASE_PUBLISHABLE_KEY",
      "VITE_SUPABASE_URL",
      "WAREHOUSE_ABS_MAX_ROWS",
      "WAREHOUSE_MAX_CONCURRENT",
      "WAREHOUSE_MAX_CONCURRENT_PER_USER",
      "WAREHOUSE_MAX_ROWS",
      "WAREHOUSE_POOL",
      "WAREHOUSE_POOL_IDLE_MS",
      "WAREHOUSE_POOL_MAX",
      "WAREHOUSE_POOL_MAX_KEYS",
      "WAREHOUSE_POOL_TTL_MS",
      "WAREHOUSE_QUERY_TIMEOUT_MS",
      "WAREHOUSE_QUEUE_TIMEOUT_MS",
      "X-Forwarded-For",
      "docs/INSTALL.md",
      "email_send_log",
      "function",
      "http://127.0.0.1:8091",
      "http://js-sandbox:8091",
      "http://localhost:8080",
      "max_connections",
      "noreply@example.com",
      "off",
      "onboarding@resend.dev",
      "true",
      "web_browse",
      "yes"
    ],
    "headings": [
      {
        "id": "quick",
        "text": "One-command setup",
        "level": 2
      },
      {
        "id": "manual",
        "text": "Manual setup",
        "level": 2
      },
      {
        "id": "env",
        "text": "Environment reference",
        "level": 2
      },
      {
        "id": "env-required",
        "text": "Required — Supabase and identity",
        "level": 3
      },
      {
        "id": "env-models",
        "text": "Models and search",
        "level": 3
      },
      {
        "id": "env-connections",
        "text": "Data connections",
        "level": 3
      },
      {
        "id": "env-email",
        "text": "Email delivery",
        "level": 3
      },
      {
        "id": "env-limits",
        "text": "Run limits and cost",
        "level": 3
      },
      {
        "id": "env-tuning",
        "text": "Performance and concurrency tuning",
        "level": 3
      },
      {
        "id": "env-network",
        "text": "Network egress",
        "level": 3
      },
      {
        "id": "env-observability",
        "text": "Observability and audit",
        "level": 3
      },
      {
        "id": "env-scheduling",
        "text": "Scheduling",
        "level": 3
      },
      {
        "id": "env-docgen",
        "text": "Document renderer",
        "level": 3
      },
      {
        "id": "env-notebooks",
        "text": "Notebook runtime",
        "level": 3
      },
      {
        "id": "recipes",
        "text": "Configuration by use case",
        "level": 2
      },
      {
        "id": "recipe-eval",
        "text": "Evaluating it on a laptop",
        "level": 3
      },
      {
        "id": "recipe-team",
        "text": "An internal tool for one team",
        "level": 3
      },
      {
        "id": "recipe-public",
        "text": "Public embeds on a marketing site",
        "level": 3
      },
      {
        "id": "recipe-regulated",
        "text": "Regulated or air-gapped",
        "level": 3
      },
      {
        "id": "recipe-fleet",
        "text": "Autoscaled behind a load balancer",
        "level": 3
      },
      {
        "id": "optional-services",
        "text": "Optional services",
        "level": 2
      },
      {
        "id": "deploy-targets",
        "text": "Deployment targets",
        "level": 2
      },
      {
        "id": "scaling",
        "text": "Scaling",
        "level": 2
      },
      {
        "id": "operations",
        "text": "Operations",
        "level": 2
      },
      {
        "id": "hardening",
        "text": "Before you expose it",
        "level": 3
      }
    ]
  },
  {
    "route": "/docs/semantics",
    "title": "Semantic Layer",
    "description": "A metric defined once and reused everywhere. It exists so that two people asking the same question of the same data cannot get two different answers.",
    "terms": [
      "0.25",
      "2026",
      "20261",
      "COUNT(*)",
      "EXISTS",
      "HAVING",
      "INNER",
      "LEFT",
      "LOCAL_ENGINE=alasql",
      "NULLIF",
      "ON",
      "SUM(orders.amount)",
      "WHERE",
      "[DEPRECATED]",
      "[certified]",
      "^[a-zA-Z_][a-zA-Z0-9_]*$",
      "_change",
      "_pct_change",
      "_prev",
      "agg",
      "avg",
      "certified",
      "compare",
      "count",
      "count_distinct",
      "currency",
      "custom",
      "customers",
      "customers.segment",
      "day",
      "deprecated",
      "derived",
      "description",
      "draft",
      "filters",
      "fiscal_period",
      "fiscal_quarter",
      "fiscal_week",
      "fiscal_year",
      "fiscal_ytd",
      "format",
      "gross_revenue",
      "label",
      "last_fiscal_period",
      "last_fiscal_quarter",
      "last_fiscal_year",
      "last_month",
      "last_n_days",
      "last_quarter",
      "many_to_many",
      "many_to_one",
      "max",
      "metric_query",
      "min",
      "mom",
      "month",
      "name",
      "net_revenue",
      "one_to_many",
      "one_to_one",
      "orders",
      "prior_period",
      "quarter",
      "revenue",
      "sql",
      "sum",
      "sum_amt_filtered",
      "this_fiscal_period",
      "this_fiscal_quarter",
      "this_fiscal_year",
      "this_month",
      "this_quarter",
      "time",
      "type",
      "week",
      "year",
      "yoy",
      "ytd"
    ],
    "headings": [
      {
        "id": "model",
        "text": "The pieces — exact fields",
        "level": 2
      },
      {
        "id": "metric",
        "text": "Metric",
        "level": 3
      },
      {
        "id": "dimension",
        "text": "Dimension",
        "level": 3
      },
      {
        "id": "define",
        "text": "Defining a metric",
        "level": 2
      },
      {
        "id": "joins",
        "text": "Joins — spanning a star schema",
        "level": 3
      },
      {
        "id": "trust",
        "text": "Trust checks — grain, measurement, assertions",
        "level": 2
      },
      {
        "id": "relative-dates",
        "text": "Relative date filters",
        "level": 3
      },
      {
        "id": "fiscal",
        "text": "Fiscal calendars",
        "level": 3
      },
      {
        "id": "rollups",
        "text": "Rollups — aggregate awareness",
        "level": 3
      },
      {
        "id": "parameters",
        "text": "Parameters — governed what-ifs",
        "level": 3
      },
      {
        "id": "hierarchies",
        "text": "Hierarchies — declared drill paths",
        "level": 3
      },
      {
        "id": "compare",
        "text": "Period-over-period",
        "level": 3
      },
      {
        "id": "agent-catalog",
        "text": "What the agent sees — synonyms, values, honest sizes",
        "level": 3
      },
      {
        "id": "worked",
        "text": "Worked example — one model, start to finish",
        "level": 2
      },
      {
        "id": "worked-1",
        "text": "1. Start from the fact table and one metric",
        "level": 3
      },
      {
        "id": "worked-2",
        "text": "2. Add the dimensions people slice by",
        "level": 3
      },
      {
        "id": "worked-3",
        "text": "3. Join the dimension table",
        "level": 3
      },
      {
        "id": "worked-4",
        "text": "4. State the grain, so a wrong join fails loudly",
        "level": 3
      },
      {
        "id": "worked-5",
        "text": "5. Add the derived metric that caused the argument",
        "level": 3
      },
      {
        "id": "worked-6",
        "text": "6. Check what the agent will see",
        "level": 3
      },
      {
        "id": "worked-7",
        "text": "7. Certify it, then share it",
        "level": 3
      },
      {
        "id": "consumers",
        "text": "Who uses it",
        "level": 2
      },
      {
        "id": "metric-vs-sql",
        "text": "Metric or plain SQL?",
        "level": 2
      },
      {
        "id": "practice",
        "text": "Practical advice",
        "level": 2
      },
      {
        "id": "access",
        "text": "Access — sharing with row-level security",
        "level": 3
      },
      {
        "id": "certification",
        "text": "Certification, history and dependents",
        "level": 3
      }
    ]
  },
  {
    "route": "/docs/skills",
    "title": "Skills & Prompt Library",
    "description": "Two small libraries of reusable text: skills are focused playbooks composed into an agent's system prompt at run time; prompts are complete starter system prompts. Both exist so good instructions get written once and reused everywhere.",
    "terms": [
      "SKILLS_INLINE_MAX_CHARS",
      "body",
      "sql_query",
      "use_skill",
      "web_search"
    ],
    "headings": [
      {
        "id": "skills",
        "text": "Skill Library",
        "level": 2
      },
      {
        "id": "loading",
        "text": "How skills reach the model",
        "level": 2
      },
      {
        "id": "skill-tool-prompt",
        "text": "Skill, tool, or just the system prompt?",
        "level": 2
      },
      {
        "id": "prompt-library",
        "text": "Prompt Library",
        "level": 2
      },
      {
        "id": "prompt-compare",
        "text": "Prompt Compare",
        "level": 2
      },
      {
        "id": "skill-fields",
        "text": "Fields on a skill",
        "level": 2
      },
      {
        "id": "writing",
        "text": "Writing one that works",
        "level": 2
      }
    ]
  },
  {
    "route": "/docs/swarms",
    "title": "Swarm Canvas",
    "description": "A swarm is a directed graph of nodes. Output flows along the edges, shared state flows through all of them. This page documents all eighteen node kinds and every field on each.",
    "terms": [
      "a2aAgentCard",
      "a2aAuthHeader",
      "a2aEndpoint",
      "a2aSkillId",
      "a2aStreaming",
      "a2a_remote",
      "agent",
      "agentId",
      "approvalRisk",
      "approvalTimeoutMs",
      "approvalTitle",
      "approverGroupIds",
      "approverUserIds",
      "array",
      "billing",
      "concat",
      "conditionPrompt",
      "continue",
      "ctx",
      "enabledTools",
      "errorFallback",
      "evalCustomInstructions",
      "evalMetrics",
      "evalPassThreshold",
      "evalReferenceInput",
      "evalRubric",
      "evaluate",
      "extract",
      "extractSchema",
      "fail",
      "first",
      "foreach",
      "foreachInput",
      "foreachItemVar",
      "function",
      "functionTimeoutMs",
      "guardrails",
      "high",
      "http",
      "httpBody",
      "httpHeaders",
      "httpMethod",
      "httpResponsePath",
      "httpTimeoutMs",
      "httpUrl",
      "inputFields[].label",
      "inputFields[].name",
      "inputFields[].options",
      "inputFields[].placeholder",
      "inputFields[].required",
      "inputFields[].type",
      "inputs",
      "knowledgeBaseId",
      "loop",
      "maxIters",
      "memory",
      "mergeSeparator",
      "message",
      "model",
      "nodeTimeoutMs",
      "none",
      "object",
      "onError",
      "options",
      "other",
      "outputVar",
      "provider",
      "refund",
      "reply",
      "reranker",
      "retrieveQuery",
      "retrieveTopK",
      "retryCount",
      "retryDelayMs",
      "return",
      "routerPrompt",
      "select",
      "skillIds",
      "stateAssignments",
      "subSwarmId",
      "swarm",
      "systemPrompt",
      "technical",
      "temperature",
      "textarea",
      "ticket",
      "tool",
      "toolArgs",
      "toolConfigs",
      "toolId"
    ],
    "headings": [
      {
        "id": "flow-state",
        "text": "Flow state and templating",
        "level": 2
      },
      {
        "id": "nodes",
        "text": "All eighteen node kinds",
        "level": 2
      },
      {
        "id": "n-input",
        "text": "input",
        "level": 3
      },
      {
        "id": "n-agent",
        "text": "agent",
        "level": 3
      },
      {
        "id": "node-memory",
        "text": "Node memory scope",
        "level": 3
      },
      {
        "id": "n-condition",
        "text": "condition",
        "level": 3
      },
      {
        "id": "n-router",
        "text": "router",
        "level": 3
      },
      {
        "id": "n-loop",
        "text": "loop",
        "level": 3
      },
      {
        "id": "n-foreach",
        "text": "foreach",
        "level": 3
      },
      {
        "id": "n-approval",
        "text": "approval",
        "level": 3
      },
      {
        "id": "n-evaluate",
        "text": "evaluate",
        "level": 3
      },
      {
        "id": "n-function",
        "text": "function",
        "level": 3
      },
      {
        "id": "n-set-var",
        "text": "set_var",
        "level": 3
      },
      {
        "id": "n-http",
        "text": "http",
        "level": 3
      },
      {
        "id": "n-tool",
        "text": "tool",
        "level": 3
      },
      {
        "id": "n-extract",
        "text": "extract",
        "level": 3
      },
      {
        "id": "n-merge",
        "text": "merge",
        "level": 3
      },
      {
        "id": "n-retrieve",
        "text": "retrieve",
        "level": 3
      },
      {
        "id": "n-subswarm",
        "text": "subswarm",
        "level": 3
      },
      {
        "id": "n-a2a",
        "text": "a2a_remote",
        "level": 3
      },
      {
        "id": "n-output",
        "text": "output",
        "level": 3
      },
      {
        "id": "errors",
        "text": "Error handling",
        "level": 2
      },
      {
        "id": "patterns",
        "text": "Patterns that recur",
        "level": 2
      },
      {
        "id": "pattern-router",
        "text": "Router to specialists",
        "level": 3
      },
      {
        "id": "pattern-pipeline",
        "text": "Pipeline",
        "level": 3
      },
      {
        "id": "pattern-fanout",
        "text": "Fan-out and merge",
        "level": 3
      },
      {
        "id": "pattern-critic",
        "text": "Generate, judge, revise",
        "level": 3
      },
      {
        "id": "pattern-gate",
        "text": "Human gate before something irreversible",
        "level": 3
      },
      {
        "id": "worked-example",
        "text": "Worked example — a support triage swarm",
        "level": 2
      },
      {
        "id": "running",
        "text": "Running and observing",
        "level": 2
      },
      {
        "id": "deploy",
        "text": "Deploying",
        "level": 2
      },
      {
        "id": "components",
        "text": "Custom components",
        "level": 2
      },
      {
        "id": "file-inputs",
        "text": "File inputs",
        "level": 2
      },
      {
        "id": "evaluations",
        "text": "Batch evaluations",
        "level": 2
      },
      {
        "id": "export",
        "text": "Export",
        "level": 2
      },
      {
        "id": "troubleshooting",
        "text": "Troubleshooting",
        "level": 2
      }
    ]
  }
];
