// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // In the browser, always call Supabase through the same origin the page
  // itself was loaded from (via a "/supabase" reverse-proxy path), instead
  // of a single origin baked into the bundle at build time. The app is
  // reachable from more than one origin (e.g. a Tailscale-only host and a
  // public host gated by Maintenance Access); a hardcoded absolute
  // VITE_SUPABASE_URL only works from whichever single origin it names and
  // silently breaks every Supabase call (login, session, etc.) from any
  // other reachable origin. SSR/server code keeps using the internal
  // SUPABASE_URL / VITE_SUPABASE_URL env value directly, since it talks to
  // the gateway over the internal network, not through a browser origin.
  const SUPABASE_URL =
    typeof window !== "undefined"
      ? `${window.location.origin}/supabase`
      : import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
